### ISSUE TITLE
brief syntax explanation

### ISSUE THREAD

**Issue by lmrhody** [DHRI-Curriculum/command-line#10]
We may also want to point out that commands are typically words, that some commands have options that help you to clarify your command so that the computer can respond more specifically. That options often follow a single dash if they're letters. (For example `ls -LP` is a command and an option. The command is to list the items in the current directory (or folder), and -LP says to list all the details. The next step is that you can take the command and the options, and you can put them someplace using a symbol... etc.... `ls -LP > contents.txt` Now if you open up the contents.txt file, you can see that you gave the computer a command "list files in the current directory" you were specific in your request "list them in long form with properties" then you told the computer to put the results in a new txt file called contents.txt. If you open the contents.txt file in a text editor like VSCode, you can see everything that is in your directory with the properties associated with them.) 

I think this kind of information, about how the command line understands your input if it follows a specific pattern could go well on the why-is-the-command-line-useful page.

**Comment by smythp** [comment]
Think there's something to be said for not frontloading too much. One pedagogical philosophy (Learn Python the Hard Way) is to show and then to explain. Think there's a little room to talk about flags and command creation toward the end and will take a look there. For now, closing this issue. Feel free to reopen and continue discussion however if you disagree.
