### ISSUE TITLE
Connecting skills learned here with next skills & review

### ISSUE THREAD

**Issue by lmrhody** [DHRI-Curriculum/command-line#15]
At the end of the lesson, how can you directly and explicitly connect the lessons they've learned in this lesson with what is coming next? For example, how does it help with learning git? How does it help with HTML/CSS or GIS or other courses along the way. 

What are the most salient take aways from the lesson? 

This is a good time to also do a quick review: 

When we started, we reviewed what the difference was between a .txt and a .rtf file was. We learned that text editors that we want to use are a kind of software that doesn't allow for formatting of font, like color and size. Text editors are a different piece of software than Bash, which is a text-based shell that allows you to interact directly with your operating system giving direct input and receiving output. We learned commands that help you navigate your computer's file system.... (etc. etc.) 

Thanks!

**Comment by jojokarlin** [comment]
I added this in summary.md. 
You'll see new sections:
### What we've learned
recaps learning objectives
ties in to upcoming lessons
### Moving Forward
which indicates use in git and outlines next tools (MALLET and pandoc) with reference to Zotero and upcoming workshops
ties in to DH projects
### What next
Links to immediate next steps -- the resources in the tutorial as well as extra challenges.
