### ISSUE TITLE
Rachel's issues

### ISSUE THREAD

**Issue by rachelrakov** [DHRI-Curriculum/command-line#17]
- Typo in section Text Editors: in the line below the visual of the word doc opened in a text editor, commandline should be two words.
- Make sure to be consistent when using etc. (make a decision to use the period or not, right now you are jumping between the two)
- For downloading Gitbash instructions, change step 2 to be on a new line.
- In spelling tips, maybe change "your spelling will be the first thing you check" to "your spelling should be the first thing you check".  Just a suggestion; does not need to be implemented
- In the 'Navigation" section, you define pwd, but do not define cd ("change directory") or list ("list").  It would be helpful, I think, to include those definitions.
- In 'Creating files and folders', might be useful to remind that mkdir stands for "make directory"
- In "Exploring Text Files", it might be useful to define what the "less" command means.  I wasn't familiar with the term paginated, but maybe others will.  Just a suggestion; does not need to be implemented.

Other than these small thing, I think your workshop looks really great!  It's very clear to me and I think it will be very well received.

**Comment by jojokarlin** [comment]
Thanks, Rachel!
