### ISSUE TITLE
MinGW/Windows navigation

### ISSUE THREAD

**Issue by story645** [DHRI-Curriculum/command-line#18]
to get to their regular files in MinGW, the path is 
```shell
/c/Users/<their username>/etc
```

**Comment by dhinstitutes** [comment]
@story645 - not sure what this is in relation to. Can you provide a bit more context to the issue?

**Comment by smythp** [comment]
Think we can close this. Hi Hannah!

**Comment by story645** [comment]
Hi! Yah this can be closed.
@dhinstitutes this was in reference to finding the homefolder (so desktop/documents/etc) using a mingw shell, but there are so many shells floating around this guide (and newer guides should probably just use windows subsystem linux 'cause it's great) that it's not something that needs to be incorporated into the guide.

**Comment by kallewesterling** [comment]
Perfect! Thank you so much!!
