### ISSUE TITLE
Broken "back" link on what-is-the-command-line.md

### ISSUE THREAD

**Issue by kchatlosh** [DHRI-Curriculum/command-line#19]

**Comment by kallewesterling** [comment]
I can't find the problem. Can you replicate it, you think? (Also: Are you sure it's in the DHRI-Curriculum or has @jojokarlin made edits in some other repo of the command-line?

**Comment by kchatlosh** [comment]
Hi Kalle, sorry my b, you are right! I had a bunch of windows open and mixed them up—that error was on the January 2018 DRI version not the DHRI workshop. Sorry again!

**Comment by kallewesterling** [comment]
No worries! I suspected that but didn't want to assume. :)
