### ISSUE TITLE
Complete assessment.md

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/command-line#54]
- [x] _Make sure you are in the right branch and have recently pulled all the content from the GitHub repository before you start working._

- [x] **Create a `assessment.md` file in the root directory of your repository**
   [Here](https://raw.githubusercontent.com/DHRI-Curriculum/guide/v2.0/template-assessment.md), you can find the template for `assessment.md`. Copy the contents into the new file in your repository.

- [x] Complete the **quantitative self-assessment** section

   - Use `## Quantitative Self-Assessment` to indicate the beginning of the section.

   - Move all the relevant quantitative self-assessment questions from DHRI/DRI exit slips found in the GCDI Google Drive over to this file.

   - Each question should be a regular paragraph.

   - Each question should have multiple choice answers, added as bullet points under the paragraph (in markdown, you use `- ` on a new line to create a bullet point).

   - Make sure that the questions enable the learner to evaluate their understanding of specific concepts from the workshop.

- [x] Complete the **qualitative self-assessment** section

   - Use `## Qualitative Self-Assessment` to indicate the beginning of the section.

   - Move all the relevant qualitative self-assessment questions from DHRI/DRI exit slips found in the GCDI Google Drive over to this file.

   - Each question should be a regular paragraph.

   - For each question, think of readings/tutorials/projects/challenges from the "Theory to Practice" section to direct them to, and add a note of that as a bullet point under relevant questions (in markdown, you use `- ` on a new line to create a bullet point).

   - Make sure that the questions enable the learner to evaluate their understanding of specific concepts from the workshop.

**Comment by smorello87** [comment]
I pulled the questions from both the DRI Exit slip (Jan 2020) and the DHRI one from 2018. Please let me know if I need to find more... it looked like the questions from 2018 and 2019 were either redundant or not specific enough.
