### ISSUE TITLE
Challenges for Introductory Lessons

### ISSUE THREAD

**Issue by smorello87** [DHRI-Curriculum/command-line#61]
Should we have challenges even for the introductory sections of our workshop (e.g., in the Command Line [lessons.md](https://github.com/DHRI-Curriculum/command-line/blob/v2.0-smorello-edits/lessons.md) "What Is the Command Line?," "Text Editors," and "Why is the command line useful?")?

**Comment by kallewesterling** [comment]
No I think it's OK to leave some of the early ones without challenges - no problem.
