### ISSUE TITLE
lessons.md reviewed

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/command-line#65]
- Look at your workshop on [the website](http://kallewesterling.pythonanywhere.com) to see what your workshop currently looks like, and what looks like it needs to change.
- Think about order and transitions—do the lessons follow a logical pattern and is it working? Do you need to add something somewhere? Are the transitions between the lessons clear?
- Can you add a challenge at the end of the lesson that summarizes what the learner has learned, and activates the knowledge in an interactive way.
- Think about the length of the lessons — are they too long? Too short? In general, each lesson should cover one topic, or one particular skill — or perhaps connect two skills. If you find that you’re covering more than that in one lesson, perhaps they should be split into more than one.
- While reviewing the lessons.md file, think about vocabulary terms that we should add in an easily accessible "dictionary" for our learners.

Feel free to reach out to me and @lmrhody and ask for help, if you need it. Also feel free to involve others in the group!

**Comment by kallewesterling** [comment]
If you want another view of the Markdown and how it is being translated/parsed into the website, you can see [this link](https://kallewesterling.pythonanywhere.com/preview). It is a new tool that I created that will download the live markdown from GitHub and preview the way that the website interprets the markdown. In order to access it, you'll have to be logged in using `admin` as your login and `admin` as your password!

Once you're logged in, you can click "Preview in parser" and it should show you what the live markdown is, and how the website will interpret your markdown.

**Comment by smorello87** [comment]
Hi Kalle! I can't seem to access the website from either link! I tried from a couple of different browsers. Attached is a screenshot of the error I receive.

<img width="960" alt="Screen Shot 2020-07-15 at 12 56 45 PM" src="https://user-images.githubusercontent.com/35434644/87537664-4189c580-c69b-11ea-85bb-eaa1c97c330b.png">

**Comment by kallewesterling** [comment]
Agh, so sorry! I have fixed it now!

(How weird that it didn't happen to me last night when I checked it!)
