### ISSUE TITLE
Not rendering images

### ISSUE THREAD

**Issue by smorello87** [DHRI-Curriculum/command-line#66]
This is what I get when I try and preview the content of the lessons.md file on Kalle's portal

<img width="413" alt="Screen Shot 2020-07-15 at 10 05 37 PM" src="https://user-images.githubusercontent.com/35434644/87590752-96532d80-c6e7-11ea-8a0b-28c1ee4f31a2.png">

This is the broken URL: https://kallewesterling.pythonanywhere.com/preview/command-line/lessons/sections/images/worddoc.png

**Comment by kallewesterling** [comment]
I'll close this issue here as it pertains more to [django-app](https://github.com/DHRI-Curriculum/django-app) than it does to your particular workshop. Thanks for letting me know!
