### ISSUE TITLE
lessons suggestions

### ISSUE THREAD

**Issue by dyoong** [DHRI-Curriculum/command-line#69]
Heya, I just have some suggestions to improve the clarity for the lessons that may be helpful to you. :)

**What does "text-based" means?**
I think there can be a little clarification between what you mean by 'text' and word processed here. The sentence that seems to be the bulk of the explanation seems a little dense (quoted below); maybe breaking it up can be helpful?
```
As we start to get comfortable typing commands to the computer, it's important to distinguish "text" from word processed, desktop publishing (think Microsoft Word or Google Docs) in which we use software that displays what we want to produce without showing us the code the computer is reading to render the formatting. 
```

**Plain text**
The comparison to rich text before the explanation at the end of the subsection may cause some confusion. Since it is not directly related to the quote, maybe the comparison can be removed until you introduced what rich text is?

**Getting to the Command Line: macOS**
Perhaps a series of screenshot/gif/screencast (like the later solutions) can be helpful to demonstrate what the navigation looks like, just in case folx are not familiar with the magnifying glass.

I'm also not sure why `You can change the color of your Terminal or BashShell background and text by selecting Shell from the top menu bar, then selecting a theme from the menu under New Window.` is in italics here. I didn't make any edits just in case it's intentional, but in case it isn't, here it is~!

**Getting to the Command Line: Windows**
Is there a resource you could link folx to for the reason why we won't use their terminal? 

Also the keyboard shortcuts to navigate to gitbash for windows is: `Win (⊞ )` > type `gitbash`>`Enter`.

**Command prompt**
I think having all of the command prompt discussion in this section will useful. The additional explanation in the macOS section can be brought in here instead.

**Creating a file**
Could you add a description to what the `touch` command does? You've done so for all the other commands so far. 

**A note on file naming**
You mentioned "report to class" here for the activity of creating a file with spaces, what could an alternative to class be in this case?

When you're suggesting how to name files, maybe you can also mention that it will be useful to avoid periods in file names too as they sometimes can be confused with system files or file extensions.

**Creating a cheatsheet: Challenge**

It may be good to remind folx what `code` does in the terminal. It was briefly mentioned in the installation guide for when folx were adding the program to path so that they can open it from the terminal (and is also the program name, so we are calling this program to open this file). This will also keep it consistent with the descriptions of commands that you've been using throughout the lesson.

**Pipes**
It may be useful to describe/explain what a flag is. You mentioned it in the section on cleaning the data, but perhaps the description can be brought forward since it is first referenced here?

**Note: Clearing text**
The keyboard shortcut is `CTRL` + `L` for windows.

**Searching text data**
A little more context to regular expression can be helpful. For example, what do you mean by infamously human illegible commands?

 

**Formatting**
I think that there can be consistency in how you're quoting functions/keys/files, you switched between ` and " through the workshop (like me in mine. >.<). 

You've also provided keyboard shortcuts to some but not all, maybe it will be useful to do it for all? 

Sorry it's so late. The suggestions are really for minor edits so I don't think they will eat too much into your next sprint? >.<

**Comment by smorello87** [comment]
Thank you, D! I was able to go through these and fix the `lessons.md` file this morning!
