### ISSUE TITLE
Add at least one evaluative question for each lesson

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/command-line#73]
At this point, the `lessons.md` file should be complete enough that you will be able to go through each lesson and come up with (at least) one evaluative question per lesson, on what the learner should have picked up from the lesson. They should be expressed in the form of multiple-choice questions, with one or more correct answers.

## How to add a multiple-choice question

**Go through the [`lessons.md`](https://github.com/DHRI-Curriculum/command-line/blob/v2.0-smorello-edits/lessons.md) file, and for each lesson, create a new section at the end (`## Evaluation`) where you will add the question and each of the answers, marking the correct ones with a `*` at the end of it. (See an example [here](https://github.com/DHRI-Curriculum/project-lab/blob/v2.0-kalle-testing-lessons/lessons.md#evaluation).)**

## Optional: Add open-ended questions

If you want to, in addition to the multiple-choice evaluative question, you can also raise an open-ended question, expressed as “Do you think you can answer this question:” As there is no easy way to programmatically understand the input in a text field to such a question (although, of course, not impossible), we will not be able to build such a functionality into the website. But we can offer open-ended questions as a feature for the learners to think further about the workshop’s contents. Perhaps they can be about an ethical aspect of the lesson?

**Comment by smorello87** [comment]
Hi @kallewesterling, just to be sure, what's the relationship (if any) between these questions (especially the open-ended ones) and those in the assessment.md file?

**Comment by kallewesterling** [comment]
Good morning @smorello87! Good question, and perhaps it would benefit all of the fellows to know the answer as I just briefly touched on it in our meeting on Monday.

Short answer: Cut whatever question you find in `assessment.md` that applies to a particular lesson, and paste it into the `lessons.md` file for the appropriate lesson.

Long answer: The `assessment.md` file was my early attempt (before we had a lot of the structure now in place) to have some form of assessment. None of it was ever implemented anywhere on the website. Now & instead, what we've decided is to tie one evaluative question to each lesson. Additionally, in our last project meeting (on Aug 24) we'll discuss more overarching questions about workshops as I think we might want (at least some of) those streamlined across workshops. But for now, if you have questions from the `assessment.md` file that you can use in a specific lesson, feel free to cut that out of the `assessment.md` file, and put it, according to the instructions in your repo issue concerning the `lessons.md` file, in the corresponding lesson. If you end up taking something from the old `assessment.md` file, it would make sense to keep it up to date, so just remember to push edits that you make in that file to your repo as well.

Let me know if you need me to clarify anything!
