### ISSUE TITLE
Question marks for folder structure

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/command-line#79]
Error in ingestion for `django-app`? Or is it something else?

@smorello87 - I'll look at it but wanted to tag you too.

**Comment by smorello87** [comment]
Hi Kalle! It looks like it's an ingestion issue, attached is how it looks
on GitHub

![Screen Shot 2020-09-18 at 8 56 14 AM](https://user-images.githubusercontent.com/35434644/93566211-f8047200-f98c-11ea-8fe7-0a81d6d95428.png)

**Comment by kallewesterling** [comment]
@smorello87 Yup, I think it has something to do with UTF-encoding on GitHub that somehow gets transformed to ASCII in the ingestion. Ugh. I don't know where though! (And I built the whole machine!)

**Comment by kallewesterling** [comment]
Opened a separate issue in `django-app`. Might go ahead and replace this text structure with a better image, but it still needs to be addressed.
