### ISSUE TITLE
Wrong Solution to Challenge in Exploring the Data lesson

### ISSUE THREAD

**Issue by smorello87** [DHRI-Curriculum/command-line#80]
Should be 

cat nypl_items.csv | uniq > new_nypl_items.csv

Instead of

cat nypl_items.csv | uniq -d > new_nypl_items.csv

**Comment by kallewesterling** [comment]
https://github.com/DHRI-Curriculum/command-line/commit/715b5da10d74e452f416cff99c0c4088ab0788e4 resolves this issue.
