### ISSUE TITLE
Need extra installation steps to launch VS Code from Terminal

### ISSUE THREAD

**Issue by smorello87** [DHRI-Curriculum/command-line#81]
https://code.visualstudio.com/docs/setup/mac 

1) Should we add it to the installation page? 
2) Need  to ask someone with a PC if this is also needed on Git Bash

**Comment by kallewesterling** [comment]
Sounds good to add this to the Mac `install` for VS Code -- I thought we already had it! I'll open an issue in that repo.

I just did some research on the Windows component of the question:
- "Setup will add Visual Studio Code to your %PATH%, so from the console you can type 'code .'" (see the [official documentation](https://code.visualstudio.com/docs/setup/windows))
- It should work natively (as far back as [2015](https://github.com/microsoft/vscode/issues/1704), in fact)

Related to this, if we would ever use VS Code's built-in terminal, we'd also have to change that to Git Bash (see this quote from [here](https://medium.com/@pyaephyokyaw_97225/customizing-path-on-windows-os-using-bashrc-and-git-bash-terminal-6832fab9422c#:~:text=Go%20to%20File%20%3E%20Preferences%20%3E%20Settings,it%20will%20prompt%20Git%20Bash.)):
> By default, VS Code built-in terminal uses Windows Command Prompt (CMD). You need to change this Windows CMD to Git Bash. Go to File > Preferences > Settings and type shell in search settings.
